clone_depth: 1
#init:
#    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

image: Visual Studio 2019

environment:
    BUILD_NO: $(APPVEYOR_BUILD_NUMBER)
    BRANCH: $(APPVEYOR_REPO_BRANCH)
    REPO: $(APPVEYOR_REPO_NAME)
    matrix:
        - MINGW_VERSION: mingw64
          ARCH: x86_64
          ARCH_BIT: 64
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          BUILD_DEPS_CMD: "C:\\msys64\\usr\\bin\\bash CI\\appveyor\\build_appveyor_mingw.sh"
          DEPLOY_FILE: "C:\\scopy-%ARCH_BIT%-setup.exe"

        - MINGW_VERSION: mingw32
          ARCH: i686
          ARCH_BIT: 32
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          BUILD_DEPS_CMD: "C:\\msys64\\usr\\bin\\bash CI\\appveyor\\build_appveyor_mingw.sh"
          DEPLOY_FILE: "C:\\scopy-%ARCH_BIT%-setup.exe"

        - ARCH: x86_64
          ARCH_BIT: 64
          APPVEYOR_BUILD_WORKER_IMAGE: macos
          BUILD_DEPS_CMD: "/Users/appveyor/projects/scopy/CI/appveyor/install_macos_deps.sh"
          BUILD_CMD: "/Users/appveyor/projects/scopy/CI/appveyor/build_appveyor_macos.sh"
          PACKAGE_CMD: "/Users/appveyor/projects/scopy/CI/appveyor/package_darwin.sh"
          DEPLOY_FILE: "/Users/appveyor/projects/scopy/build/Scopy.dmg"
          C_COMPILER: -DCMAKE_C_COMPILER=/usr/bin/gcc
          CXX_COMPILER: -DCMAKE_CXX_COMPILER=/usr/bin/g++

        - ARCH: x86_64
          ARCH_BIT: 64
          APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
          BUILD_DEPS_CMD: "/Users/appveyor/projects/scopy/CI/appveyor/install_macos_deps.sh"
          BUILD_CMD: "/Users/appveyor/projects/scopy/CI/appveyor/build_appveyor_macos.sh"
          PACKAGE_CMD: "/Users/appveyor/projects/scopy/CI/appveyor/package_darwin.sh"
          DEPLOY_FILE: "/Users/appveyor/projects/scopy/build/Scopy.dmg"
          C_COMPILER: -DCMAKE_C_COMPILER=/usr/bin/gcc
          CXX_COMPILER: -DCMAKE_CXX_COMPILER=/usr/bin/g++

        - ARCH: x86_64
          ARCH_BIT: 64
          APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
          BUILD_DEPS_CMD: "/home/appveyor/projects/scopy/CI/appveyor/install_ubuntu_deps.sh /home/appveyor/Qt/5.14.2"
          BUILD_CMD: "/home/appveyor/projects/scopy/CI/appveyor/build_appveyor_ubuntu.sh /home/appveyor/Qt/5.14.2"
          PACKAGE_CMD: ""
          DEPLOY_FILE: ""

#        - ARCH: x86_64
#          ARCH_BIT: 64
#          APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
#          BUILD_DEPS_CMD: "/home/appveyor/projects/scopy/CI/appveyor/build_appveyor_flatpak.sh $BRANCH $REPO"
#          BUILD_CMD: ""
#          PACKAGE_CMD: ""
#          DEPLOY_FILE: "/home/appveyor/projects/scopy/Scopy.flatpak"

install:
    # Install Inno Setup
    - cmd: choco install InnoSetup

build_script:
    - cmd: C:\msys64\usr\bin\bash -lc "/c/projects/scopy/CI/appveyor/extract_msys_deps.sh"
    - cmd: C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu"
    - cmd: set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 6"
    - cmd: "%BUILD_DEPS_CMD%"

    - sh: echo $BUILD_DEPS_CMD
    - sh: $BUILD_DEPS_CMD
    - sh: $BUILD_CMD
    - sh: $PACKAGE_CMD

    - echo "### Push artifacts ... "
    - cmd: appveyor PushArtifact c:\scopy-%ARCH_BIT%bit.zip
    - cmd: appveyor PushArtifact C:\debug-%ARCH_BIT%bit.zip
   
    #- cmd: appveyor PushArtifact %DEPLOY_FILE%
    #- sh: if [[ $DEPLOY_FILE != "" ]]; then appveyor PushArtifact $DEPLOY_FILE; fi

#on_finish:
#    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
